### ISSUE TITLE
Workshop Impact Plot

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [carpentries/assessment-projects#13]
A few things...

- Plot is mislabeled (Workshops are welcoming and useful)?
- Y axis 1 and 2 have percentages, are those the Strongly disagree and Strongly agree? I was confused
- Y axis labels will have to be fixed to remove '.'
- Legend is cut off

**Comment by kariljordan** [comment]
I fixed the plot label. It now says "Perception of Workshop Impact"

Yes, the percentages are the strongly disagree to strongly agree (same as the key on the bottom of the plot).

I revised the axis labels. Unfortunately, I can't figure out how to have more than one word in a label without there being a period between the words. I tried to come up with labels that make sense. One problem though is that now the labels are out of order. I'm working on fixing this, and the legend.

**Comment by kariljordan** [comment]
Fixed.
