### ISSUE TITLE
Calculations for Behaviors Respondents adopted

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [carpentries/assessment-projects#14]
n for this question is 361, so if 260 used languages, that's 72%. Would that be better to report according to n for the question? Even for the n=476, this would be almost 55% no?

**Comment by kariljordan** [comment]
Jason, that is SUCH A GOOD CATCH! GAWD!

So what is happening is that this was a "check all that apply" question. I will get with @benmarwick to see how to fix this because he helped me with the function that calculates the %'s in the tables. Great catch!

**Comment by benmarwick** [comment]
Yes, great observation! I've tried to fix this for most questions in #27

**Comment by kariljordan** [comment]
You all rock!
