### ISSUE TITLE
Matrix of Common Behaviors Adopted Post-Workshop 

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [carpentries/assessment-projects#15]
I am not sure I understand the purpose of this plot (forgive me I'm dense - really!). What do we really want to say here? That some behaviors are adopted as a group? This would also be difficult (I think) from our survey since if all participants weren't exposed to the same curriculum I am not sure what we could say. Finally, I would guess percentages would work better here?

**Comment by kariljordan** [comment]
This was another check all that apply question, so we're trying to see what combinations are the highest checked. For example, 122 people checked **using programming to automate tasks** and **improve management and project organization**. @tracykteal had the idea of generating a heat map to show the high frequencies, so we're working on that.

**Comment by JasonJWilliamsNY** [comment]
Hmm... my fear was that although we can calculate that, what can we conclude if respondents weren't all exposed to the same curriculum, and presumably could not have adopted certain behaviors.

**Comment by kariljordan** [comment]
That's a great thought. I will add it to the section on growth opportunities right now and close this issue. Soooo good Jason!
