### ISSUE TITLE
Change in Confidence/ and Comparing post- and long-term results

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [carpentries/assessment-projects#16]
Would this be a good place to ask about how this question relates to our data on learner confidence immediately post-workshop? On average, are confidence gains still there 6 months + post-workshop?

**Comment by kariljordan** [comment]
In the post-workshop survey we did not ask about confidence directly, but we did ask if they had a better understanding of how to import data into R, organize data, etc. I added a few sentences that point to those results to basically show that the long-term survey is consistent with the post-workshop surveys for both SwC and DC.
