### ISSUE TITLE
Rendering markdown from R script

### ISSUE THREAD

**Issue by kariljordan** [carpentries/assessment-projects#17]
@orchid00 created this [script](https://github.com/carpentries/assessment-projects/blob/master/data-carpentry-projects/archived-survey-data/scripts/calls.R) that will produce plots for our pre and post workshop data. The script calls another [script](https://github.com/carpentries/assessment-projects/blob/master/data-carpentry-projects/archived-survey-data/scripts/exploringData.R) that was used to clean the data, and a second [script](https://github.com/carpentries/assessment-projects/blob/master/data-carpentry-projects/archived-survey-data/scripts/installpkg.R) that was used to install the packages.

I would like to create the RMD report from the calls.R [script](https://github.com/carpentries/assessment-projects/blob/master/data-carpentry-projects/archived-survey-data/scripts/calls.R). I read [here](https://stackoverflow.com/questions/31324236/accessing-data-generated-by-an-r-script-with-r-markdown-and-knitr) and [here](http://brooksandrew.github.io/simpleblog/articles/render-reports-directly-from-R-scripts/) that it's possible, but when I use:

rmarkdown::render('Users/Data_Carpentry/my-forked-repos/assessment-projects/data-carpentry-projects/archived-survey-data/scripts/calls.R')

at the end of [calls.R](https://github.com/carpentries/assessment-projects/blob/master/data-carpentry-projects/archived-survey-data/scripts/calls.R)

I get this error message:
Error in tools::file_path_as_absolute(input) : 
  file 'Users/Data_Carpentry/my-forked-repos/assessment-projects/data-carpentry-projects/archived-survey-data/scripts/calls.R' does not exist
In addition: Warning message:
In normalizePath(path, winslash = winslash, mustWork = mustWork) :
  path[1]="Users/Data_Carpentry/my-forked-repos/assessment-projects/data-carpentry-projects/archived-survey-data/scripts/calls.R": No such file or directory

I would appreciate any help!

**Comment by ctb** [comment]
What happens if you use `/Users/Data_Carpentry/my-forked-repos/assessment-projects/data-carpentry-projects/archived-survey-data/scripts/calls.R` instead? The prefix '/' makes it an absolute path.

**Comment by ctb** [comment]
The shell command `ls Users/Data_Carpentry/my-forked-repos/assessment-projects/data-carpentry-projects/archived-survey-data/scripts/calls.R` should show you that the file does not exist, while `ls /Users/Data_Carpentry/my-forked-repos/assessment-projects/data-carpentry-projects/archived-survey-data/scripts/calls.R` should show `calls.R` if that's the right path.

**Comment by kariljordan** [comment]
Yikes! I realized the path was incorrect. It should've been:

ls /Users/kariljordan/Data_Carpentry/my-forked-repos/assessment-projects/data-carpentry-projects/archived-survey-data/scripts/calls.R
I forgot the kariljordan. DUH!

So I ran it and got this error:

Quitting from lines 3-18 (calls.spin.Rmd) 
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection

I'm going to work on figuring out why. I can't believe I didn't notice that file path error. UGH!

**Comment by ctb** [comment]
happens to me all the time!

**Comment by jvcasillas** [comment]
The main issues is that ```rmarkdown::render()``` is called on a .R file. This function works with rmarkdown files. If you want to create an .html document from an .R script you need to use ```knitr::spin()```. Here is a zip file that should be reproducible. https://www.dropbox.com/s/bkmgml0o1yno15z/reprex.zip?dl=0

Check the "calls.html" file.

**Comment by orchid00** [comment]
@kariljordan   just to clarify a little bit, you should just "render" or "spin" the script "exploringData.R" then when you are writing the RMD you can add the lines of code that you need from the "calls.R" script.

**Comment by kariljordan** [comment]
@jvcasillas You have no idea how helpful this is. I appreciate you so much for taking a look! 

When I do this:
```
setwd("~/Users/kariljordan/Data_Carpentry/my-forked-repos/assessment-projects/data-carpentry-projects/pre-and-post-analysis/archived-survey-analysis")

knitr::spin("./scripts/calls.R")
```

I receive this error message:
```
output file: calls.md

Warning messages:
1: In grid.Call.graphics(C_upviewport, as.integer(n)) :
  cannot pop the top-level viewport ('grid' and 'graphics' output mixed?)
2: In UseMethod("depth") :
  no applicable method for 'depth' applied to an object of class "NULL"
```
My [calls.html](https://github.com/carpentries/assessment-projects/blob/master/data-carpentry-projects/pre-and-post-workshop-analysis/archived-survey-analysis/calls.html) and [calls.md](https://github.com/carpentries/assessment-projects/blob/master/data-carpentry-projects/pre-and-post-workshop-analysis/archived-survey-analysis/calls.md) files are [here](https://github.com/carpentries/assessment-projects/tree/master/data-carpentry-projects/pre-and-post-workshop-analysis/archived-survey-analysis).

I'm going to check Stackoverflow now about these error messages, but wanted to update this issue. It's so great to be a part of this community--people want to help! Thank you!

**Comment by kariljordan** [comment]
@orchid00 I saw your comment after I did the wrong thing, so now I'm going to try what you suggested. Thank you!

**Comment by kariljordan** [comment]
@jvcasillas Any idea what this error message means?

```
Error: 'spin' is not an exported object from 'namespace:rmarkdown'
```
There isn't a good solution on StackOverflow...

**Comment by orchid00** [comment]
So this is the working code, saved in a file called report.RMD located at the ROOT of the project. The render report looks pretty:  [see report in my repo](https://github.com/orchid00/ExploringSurveyDC/blob/master/report.md)

```
---
title: "Report Data Carpentry Assessment"
author: "Kari L. Jordan and Paula Andrea Martinez"
date: "12 September 2017"
output: github_document
---

```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(error = FALSE)
```

## R Markdown

This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML.


```{r calls, echo = FALSE, message = FALSE, warning = FALSE}
source(file = "scripts/calls.R")
```
```

**Comment by kariljordan** [comment]
It works! 

[report](https://github.com/carpentries/assessment-projects/blob/master/data-carpentry-projects/pre-and-post-workshop-analysis/archived-survey-analysis/archived_survey_report.md)

**Comment by ctb** [comment]
yay!
