### ISSUE TITLE
Add caption to "Perception of workshop impact" figure?

### ISSUE THREAD

**Issue by naupaka** [carpentries/assessment-projects#24]
I am not sure what the percentages mean in this figure.

**Comment by kariljordan** [comment]
<img width="997" alt="screen shot 2017-09-13 at 3 58 17 pm" src="https://user-images.githubusercontent.com/21027863/30397911-63e8550e-989c-11e7-9467-7b708d83285a.png">

@tracykteal had the same comment. Does this make it more clear?

**Comment by naupaka** [comment]
I still don't get what the numbers mean. There are three percentages for each row but 5 colors...

**Comment by kariljordan** [comment]
Ah! I see what you mean now @naupaka.

Here is the code:
```
# Jonah's fix to include the correct levels. Variable was renamed to 'levels' #because 'order' is the name of a function in R.
# I am still not sure if this plot is 100% correct -KLJ

cols_with_Agree <- map_lgl(data, ~`%in%`("Agree", .x))
data_agree <-  data[ , cols_with_Agree]

levels = c("Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree")

# Beth's tip to both order the factors based on levels and unify the factors
 factorfunction <- function(mydata, factlevel){
  factor(mydata, 
         levels=factlevel, 
         ordered = TRUE)
    fct_unify(mydata, 
              levels=factlevel)}
 # End tip 
 
 # Adjusting names of y axis labels
 names(data_agree) <- 
  c("Coding",
    "Confidence",
    "Career",
    "Motivation",
    "Reproducible",
    "Productivity",
    "Recognition")

data_agree_likert <- likert(data.frame(lapply(data_agree, factor, levels, ordered=TRUE)))
# Elizabeth's tip on factors
#for(i in seq_along(data_agree)) {
                #data_agree[[i]] <- factor(data_agree[[i]], levels=order)}

#print(levels(data_agree))
 
title <- "Perception of Workshop Impact"
 theme_update(plot.title = element_text(hjust = 0.5))
plot(data_agree_likert) + ggtitle(title) 

#print(class(data_agree))
 data_agree <- map_if(data_agree,
                     is.character,
                     as.factor)
 ggsave("figures/workshop_impact.png")
 # The plot works, but the labels are not in the correct order.
```

When I used `print(data_agree_likert)` to see what the percentages were it gave me:
```
          Item Strongly disagree  Disagree   Neutral    Agree Strongly agree
1       Coding          4.400978  7.090465 25.427873 43.76528      19.315403
2   Confidence          2.941176  2.450980  9.313725 50.73529      34.558824
3       Career          4.156479  7.334963 33.985330 35.20782      19.315403
4   Motivation          9.090909 27.027027 39.312039 17.69042       6.879607
5 Reproducible          4.400978  7.823961 18.337408 49.63325      19.804401
6 Productivity          4.901961  9.558824 33.823529 37.50000      14.215686
7  Recognition          4.166667  4.411765 26.715686 45.58824      19.117647
```

The percentage for **Neutral** is correct, and it looks like the percentage on the right of the plot is the sum of **Agree** and **Strongly Agree**. The percentage on the left of the plot is the sum of **Disagree** and **Strongly Disagree**. Would you happen to have a recommendation for how to get all of the percentages to show? Also, I'm wondering why the order in the plot doesn't reflect the order I set here:
```
 names(data_agree) <- 
  c("Coding",
    "Confidence",
    "Career",
    "Motivation",
    "Reproducible",
    "Productivity",
    "Recognition")
```

**Comment by tracykteal** [comment]
My first interpretation of the percentages would be that for instance:

For Confidence is 5% Strongly disagree, 9% Neutral and 85% Strongly agree. But that clearly isn't the case because that 'strongly agree' coloring is not 85% of the graph.

From the table, I see that for confidence it's 

Strongly disagree + disagree = 5%
Neutral = 9%
Agree + strongly agree = 85%

So I get where the numbers are coming from and now see where the numbers are coming from, but I agree it's not easy to understand at a glance. So, I don't think it should be presented this way, but am not quite sure an alternative to suggest. @naupaka do you have ideas?

**Comment by kariljordan** [comment]
I changed it to a heat map, but need to figure out the axis labels. Closing this issue.
<img width="1117" alt="screen shot 2017-09-15 at 3 27 25 pm" src="https://user-images.githubusercontent.com/21027863/30501359-25f950e6-9a30-11e7-8452-ffaf355682ae.png">
