### ISSUE TITLE
Discrepancy in tables and text in Long Term Impacts report.

### ISSUE THREAD

**Issue by bsmith89** [carpentries/assessment-projects#6]
_I originally opened this issue as kariljordan/carpentry-assessment-projects#18_

The text under the heading **Contributions to Academic Writing** appears to contradict the associated table.

**The table:**

Response | n
-- | --
No. | 44
Not sure. | 28
Yes. | 27

**The text:**

> 44 of our respondents said that the tools they learned _contributed_ to their academic writing. [emphasis mine]

If this is in fact contradictory (and I'm not just misinterpreting), I think the problem comes from [hard-coding](https://github.com/carpentries/assessment-projects/blame/master/joint-carpentry-projects/report.rmd#L888) the tally entry in the report text.

The same thing appears to be going on under **Continuous Learning**.

Under **Involvement in the Carpentries** [the number 16 is itself hard-coded in the text](https://github.com/carpentries/assessment-projects/blame/master/joint-carpentry-projects/report.rmd#L982), and has now deviated from the number in the dynamically generated table.

**Comment by tracykteal** [comment]
Thanks, good point. It makes sense to put these as a variables in the text as well as the tables.

**Comment by kariljordan** [comment]
@bsmith89 thank you so much for catching this! I just need to fix the code. I wanted to use code to pull the numbers so that I don't have to go in and change them manually whenever we release new data. Thanks!
