### ISSUE TITLE
Carpentries-specific terms

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [carpentries/assessment-projects#7]
Found a sentence:

>  positive sticky note workshop feedback 

I am assuming this will have wide circulation, so perhaps we can review to remove or explain terms that are carpentry specific?

**Comment by kariljordan** [comment]
@weaverbel Can you address this issue when you have a chance?

**Comment by kariljordan** [comment]
This will be for our community (see Tracy's [comments](https://github.com/carpentries/assessment-projects/issues/8)), but the paper Ben and I are working on will be for a broader audience, so we will explain our teaching practices (sticky notes, etc.)
