### ISSUE TITLE
Who is the target audience?

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [carpentries/assessment-projects#8]
This is a topic up for discussion. I get the sense that this is meant as an initial update to the community. There are certain phrases or comments that I think would be more targeted to a community, but some that I would not write in a publication. Is the plan to have multiple write-ups of the results? If So I can stop nitpicking! 

This thought came up at this sentence

> taking it out of the realm of ‘opinion’ or ‘feeling’, which, while interesting, is not as robust or reliable a marker of success as demonstrable evidence. 

I would have phrased it differently so that we aren't discounting attitudinal assessment, but just emphasizing our desire to demonstrate knowledge gains. This is actually an important topic (but maybe for a publication) on why we specifically avoided some questions on workshop surveys so that learners would not feel pressured. 

Knowing the audience would help me read more appropriately.

**Comment by kariljordan** [comment]
@jduckles @tracykteal My thoughts are that this report is for the community. What say you? It will help @weaverbel and I adjust the language of the report where necessary.

**Comment by tracykteal** [comment]
We see this report as being for the general community and beyond. It's an opportunity for people outside our community to see the impact of this type of training. A model for the report is something like The GitHub Open Source Survey http://opensourcesurvey.org/2017/

**Comment by JasonJWilliamsNY** [comment]
Sounds good. I wasn't sure if this would also be published. Close?

**Comment by tracykteal** [comment]
There will also be a publication. @benmarwick and @kariljordan have started working on one that puts the report results into a broader context. So, they have more information on that.

**Comment by kariljordan** [comment]
Awesome! Closing this issue.
