### ISSUE TITLE
Software vs. Data Carpentry Workshops

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [carpentries/assessment-projects#9]
Is there a way to tell if the learner/respondent took a Software or a Data Carpentry Workshop?

**Comment by JasonJWilliamsNY** [comment]
Reading on, I guess we don't know. This makes the section on Workshop Content a little confusing. Since workshop instructors have some leverage on what they will teach, this is something we should be able to know outside of the long-term survey. I think a reviewer would ask why we are trying to figure that out here. Perhaps there should be some explanation of the choice to do a 'Carpentries' survey rather than stratifying by workshop type?

**Comment by kariljordan** [comment]
We address the Carpentries survey in the introduction, and in this paragraph:

> We are outcome-driven organizations interested in continually improving the workshop experience for both our learners and our instructors. Additionally, we are largely volunteers. In order to continue our valuable work of teaching skills to researchers, we need supportive funding either from grant-making bodies or from member institutions, or - ideally - from both. Our case for funding is strengthened if we can provide impartial evidence that proves our workshops have the outcomes we claim.

**Comment by JasonJWilliamsNY** [comment]
Hmm... my criticism was not about the organizational structure, but about how (can) we compare learners in a Software vs. Data Carpentry workshop. I think there are several significant differences. I am worried that if these differences exist/matter we can't tell if we didn't have a question that asks what type of workshop they took. Does that make sense?

**Comment by tracykteal** [comment]
Hmm, that's a good point. Can we easily separate out responses from Data Carpentry versus Software Carpentry? I know there weren't as many Data Carpentry workshops though, so there might not even be that many Data Carpentry responses. It would be good to know though.

So, I guess first pass would be how many people took SWC workshops and how many DC in the responses?

**Comment by JasonJWilliamsNY** [comment]
maybe @kariljordan could comment, but my guess is that the next round of surveys should ask that question so that we can separate the two groups.

**Comment by tracykteal** [comment]
That would be good to add that question. We would also potentially want to add what type of workshop, e.g. Genomics Data Carpentry, or Library Carpentry. So there can be several options.

**Comment by kariljordan** [comment]
In the current survey the only way to separate DC from SwC is to look at what tools were covered and assume that those that learned Git/Shell/Python are SwC. For that reason, I added these questions:

```
Is this your first time completing this survey?
-Yes
-No
-I don't know.
```
```
Which Carpentries workshop did you last attend?
-Data Carpentry
-Library Carpentry
-Software Carpentry
-I don't know.
```
